<?php
/**
 ** Implements hook_theme().
 **/
function tac_vimeo_embed_field_theme($existing, $type, $theme, $path) {

  $templates = $path . '/templates';

  $return['video_embed_iframe__vimeo'] = [
    'template' => 'video-embed-iframe--vimeo',
    'path' => $templates,
      'variables' => [
        'url' => '',
        'query' => [],
        'attributes' => [],
        'fragment' => '',
    ],
  ];
  return $return;
}