<?php

use Drupal\adimeo_domain\Manager\DomainAccessPluginHandlerManager;
use Drupal\adimeo_domain\Manager\DomainManager;
use Drupal\Core\Access\AccessResultNeutral;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_access().
 */
function adimeo_domain_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  /**
   * @var \Drupal\adimeo_domain\Manager\DomainAccessPluginHandlerManager $accessPluginHandler
   */
  $accessPluginHandler = Drupal::service(DomainAccessPluginHandlerManager::SERVICE_NAME);

  /**
   * @var \Drupal\adimeo_domain\Manager\DomainManager $domainManager
   */
  $domainManager = Drupal::service(DomainManager::SERVICE_NAME);

  $accessPlugin = $accessPluginHandler->handle($domainManager->getCurrentDomainId());
  return $accessPlugin ? $accessPlugin->checkAccess($entity, $operation, $account) : AccessResultNeutral::neutral();
}